server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: bc12
          uri: http://localhost:8081
          predicates:
            - Path=/aggs/** 
        - id: BoundedContext248
          uri: http://localhost:8082
          predicates:
            - Path= 
        - id: BoundedContext693
          uri: http://localhost:8083
          predicates:
            - Path=/asdasdddds/** 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: bc12
          uri: http://bc12:8080
          predicates:
            - Path=/aggs/** 
        - id: BoundedContext248
          uri: http://boundedContext248:8080
          predicates:
            - Path= 
        - id: BoundedContext693
          uri: http://boundedContext693:8080
          predicates:
            - Path=/asdasdddds/** 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
