---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc12
  labels:
    app: bc12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bc12
  template:
    metadata:
      labels:
        app: bc12
    spec:
      containers:
        - name: bc12
          image: username/bc12:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext248
  labels:
    app: BoundedContext248
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext248
  template:
    metadata:
      labels:
        app: BoundedContext248
    spec:
      containers:
        - name: BoundedContext248
          image: username/BoundedContext248:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext693
  labels:
    app: BoundedContext693
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext693
  template:
    metadata:
      labels:
        app: BoundedContext693
    spec:
      containers:
        - name: BoundedContext693
          image: username/BoundedContext693:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: bc12
  labels:
    app: bc12
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bc12


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext248
  labels:
    app: BoundedContext248
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext248


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext693
  labels:
    app: BoundedContext693
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext693

